Repository xkjyeah/vue-google-maps, pull requests merged in 2019-10, with the labels that each got.

#640 Added initial kml layer support
  .gitignore
  README.md
  examples/basic-kml-layer.html
  package-lock.json
  package.json
  src/components/kmlLayer.js
  src/main.js
Labels: changes requested ✋

#652 recycle google.maps.Map object to reduce number of billed dynamic map loads
  .gitignore
  dist/.babelrc
  dist/vue-google-maps.js
  package.json
  src/components/mapImpl.js
Labels: ready to merge 👍, ready to review 👀

#659 Added ability to customize input using input named scoped slot
  README.md
  src/components-implementation/autocomplete.js
  src/components/autocomplete.vue
Labels: ready to merge 👍
